export const authStyles: any = {
    pageBackground: {
        backgroundColor: '#0f172a',
        backgroundImage: `
            linear-gradient(rgba(255, 255, 255, 0.03) 1px, transparent 1px),
            linear-gradient(90deg, rgba(255, 255, 255, 0.03) 1px, transparent 1px),
            radial-gradient(circle at 20% 30%, rgba(59, 130, 246, 0.3) 0%, rgba(0,0,0,0) 60%),
            radial-gradient(circle at 80% 70%, rgba(99, 102, 241, 0.3) 0%, rgba(0,0,0,0) 60%)
        `,
        backgroundSize: '30px 30px, 30px 30px, 100% 100%, 100% 100%',
        backgroundPosition: 'center center',
    },
    container: {
        minHeight: '100vh',
        width: '100%',
        position: 'relative',
        overflow: 'hidden',
        background: '#0f172a',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        padding: '20px',
        fontFamily: "'Inter', sans-serif",
        zIndex: 1,
    },
    blobBase: {
        position: 'absolute',
        borderRadius: '50%',
        filter: 'blur(80px)', // Reduzi um pouco o blur para performance
        opacity: 0.5,
        zIndex: -1,
    },
    blob1: {
        top: '10%',
        left: '10%',
        width: '60vw', // Responsivo: 60% da largura da tela
        maxWidth: '450px', // Trava no tamanho máximo
        height: '60vw',
        maxHeight: '450px',
        background: '#4338ca',
        animation: 'moveFirst 25s infinite ease-in-out alternate',
    },
    blob2: {
        bottom: '10%',
        right: '10%',
        width: '50vw',
        maxWidth: '400px',
        height: '50vw',
        maxHeight: '400px',
        background: '#3b82f6',
        animation: 'moveSecond 20s infinite ease-in-out alternate',
    },
    glassCard: {
        width: '100%',
        maxWidth: '400px',
        padding: '40px 30px',
        borderRadius: '24px',
        background: 'rgba(255, 255, 255, 0.03)',
        boxShadow: '0 4px 30px rgba(0, 0, 0, 0.2)',
        backdropFilter: 'blur(20px)',
        WebkitBackdropFilter: 'blur(20px)',
        border: '1px solid rgba(255, 255, 255, 0.1)',
        color: '#ffffff',
        zIndex: 10,
    },
    brandContainer: {
        textAlign: 'center',
        marginBottom: '40px',
    },
    brandTitle: {
        fontFamily: "'Poppins', sans-serif",
        fontSize: '36px',
        fontWeight: '800',
        background: 'linear-gradient(135deg, #60a5fa 0%, #a78bfa 100%)',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        marginBottom: '5px',
        letterSpacing: '-1px',
    },
    brandSubtitle: {
        fontSize: '14px',
        color: 'rgba(255, 255, 255, 0.6)',
        fontWeight: '300',
    },
    title: {
        fontSize: '24px',
        fontWeight: '600',
        marginBottom: '25px',
        textAlign: 'left',
        color: 'rgba(255, 255, 255, 0.9)',
    },
    inputGroup: {
        position: 'relative' as 'relative',
        marginBottom: '20px',
    },
    inputIcon: {
        position: 'absolute' as 'absolute',
        left: '0',
        top: '50%',
        transform: 'translateY(-50%)',
        color: 'rgba(255, 255, 255, 0.6)',
        fontSize: '20px',
        display: 'flex',
        alignItems: 'center',
    },
    passwordToggleIcon: {
        position: 'absolute' as 'absolute',
        right: '0',
        top: '50%',
        transform: 'translateY(-50%)',
        color: 'rgba(255, 255, 255, 0.6)',
        cursor: 'pointer',
        fontSize: '20px',
        display: 'flex',
        alignItems: 'center',
    },
    inputField: {
        width: '100%',
        padding: '12px 30px 12px 35px',
        background: 'transparent',
        border: 'none',
        borderBottom: '1px solid rgba(255, 255, 255, 0.3)',
        color: 'white',
        fontSize: '16px',
        outline: 'none',
        transition: 'border-color 0.3s',
    },
    actionsRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '30px',
        fontSize: '14px',
        color: 'rgba(255, 255, 255, 0.8)',
    },
    rememberMeToggle: {
        display: 'flex',
        alignItems: 'center',
        cursor: 'pointer',
    },
    toggleInput: { display: 'none' },
    toggleSlider: {
        position: 'relative' as 'relative',
        width: '36px',
        height: '20px',
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: '20px',
        marginLeft: '10px',
        transition: '0.3s',
    },
    toggleSliderActive: { backgroundColor: '#3b82f6' },
    toggleKnob: {
        position: 'absolute' as 'absolute',
        top: '2px',
        left: '2px',
        width: '16px',
        height: '16px',
        backgroundColor: 'white',
        borderRadius: '50%',
        transition: '0.3s',
    },
    toggleKnobActive: { transform: 'translateX(16px)' },
    link: {
        color: 'rgba(255, 255, 255, 0.8)',
        textDecoration: 'none',
        cursor: 'pointer',
    },
    mainButton: {
        width: '100%',
        padding: '15px',
        border: 'none',
        borderRadius: '12px',
        background: 'linear-gradient(90deg, #3b82f6, #60a5fa)',
        color: 'white',
        fontSize: '18px',
        fontWeight: 'bold',
        cursor: 'pointer',
        boxShadow: '0 4px 15px rgba(59, 130, 246, 0.4)',
        transition: 'transform 0.2s',
    },
    switchFormText: {
        textAlign: 'center',
        marginTop: '20px',
        color: 'rgba(255, 255, 255, 0.6)',
        fontSize: '14px',
    },
    switchFormLink: {
        color: '#60a5fa',
        fontWeight: 'bold',
        cursor: 'pointer',
        marginLeft: '5px',
        textDecoration: 'none',
    }
};
